version: '3.5'
volumes:
  data:
services:
  windows:
    image: ghcr.io/dockur/windows:latest
    container_name: linuxoffice 
    environment:
      VERSION: "tiny11"
      RAM_SIZE: "4G" # RAM allocated to the Windows VM.
      CPU_CORES: "2" # CPU cores allocated to the Windows VM.
      DISK_SIZE: "20G" # Size of the primary hard disk.
      USERNAME: "MyWindowsUser" # Edit here to set a custom Windows username. The default is 'MyWindowsUser'.
      PASSWORD: "MyWindowsPassword"
    privileged: true 
    ports:
      - 8006:8006 # Map '8006' on Linux host to '8006' on Windows VM --> For VNC Web Interface @ http://127.0.0.1:8006.
      - 3389:3389/tcp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
      - 3389:3389/udp # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
    stop_grace_period: 120s
    restart: on-failure
    volumes:
      - data:/storage # Mount volume 'data' to use as Windows 'C:' drive.
      - /linuxoffice/office:/shared # Mount Linux user home directory @ '\\host.lan\Data'.
      #- /opt/linuxoffice/tiny11.iso:/custom.iso # Lokal iso kullanmak için # işaretini silin.
    devices:
      - /dev/kvm
